# Generated by Django 5.2.5 on 2025-08-29 18:44

import django.db.models.deletion
import main.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Опциональный заголовок галереи",
                        max_length=120,
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("valentine", "14 февраля"),
                            ("womens_day", "8 марта"),
                            ("birthday", "День рождения"),
                            ("anniversary", "Годовщина"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("template_key", models.CharField(default="default", max_length=64)),
                ("first_opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "view_pin",
                    models.CharField(
                        blank=True,
                        help_text="Необязательный PIN на просмотр",
                        max_length=12,
                    ),
                ),
                (
                    "upload_pin",
                    models.CharField(
                        blank=True,
                        help_text="Необязательный PIN на загрузку",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="galleries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=main.models.media_upload_path)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("auto", "Определять автоматически"),
                            ("image", "Изображение"),
                            ("video", "Видео"),
                        ],
                        default="auto",
                        max_length=8,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Показывать как обложку/первым"
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "duration_sec",
                    models.PositiveIntegerField(
                        blank=True, default=0, help_text="Для видео, если нужно"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="main.gallery",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="main.gallery",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="QRTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.CharField(blank=True, db_index=True, max_length=40)),
                (
                    "token",
                    models.CharField(
                        default=main.models.generate_token_hex,
                        max_length=36,
                        unique=True,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_tags",
                        to="main.gallery",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="main_qrtag_token_21efb6_idx")
                ],
            },
        ),
    ]
