# Generated by Django 5.2.5 on 2025-11-07 09:09

import django.db.models.deletion
import main.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Опциональный заголовок галереи",
                        max_length=120,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("valentine", "14 февраля"),
                            ("womens_day", "8 марта"),
                            ("birthday", "День рождения"),
                            ("anniversary", "Годовщина"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="Повод",
                    ),
                ),
                (
                    "template_key",
                    models.CharField(
                        default="default", max_length=64, verbose_name="Шаблон"
                    ),
                ),
                (
                    "first_opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Первое открытие"
                    ),
                ),
                (
                    "view_pin",
                    models.CharField(
                        blank=True,
                        help_text="Необязательный PIN на просмотр",
                        max_length=12,
                        verbose_name="PIN для просмотра",
                    ),
                ),
                (
                    "upload_pin",
                    models.CharField(
                        blank=True,
                        help_text="Необязательный PIN на загрузку",
                        max_length=12,
                        verbose_name="PIN для загрузки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="galleries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Галерея",
                "verbose_name_plural": "Галереи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=main.models.media_upload_path, verbose_name="Файл"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("auto", "Определять автоматически"),
                            ("image", "Изображение"),
                            ("video", "Видео"),
                        ],
                        default="auto",
                        max_length=8,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Показывать как обложку/первым",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME-тип"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, verbose_name="Размер файла (байт)"
                    ),
                ),
                (
                    "duration_sec",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Для видео, если нужно",
                        verbose_name="Длительность (сек)",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="main.gallery",
                        verbose_name="Галерея",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_media",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем загружено",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медиафайл",
                "verbose_name_plural": "Медиафайлы",
                "ordering": ["sort_order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время посещения"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="main.gallery",
                        verbose_name="Галерея",
                    ),
                ),
            ],
            options={
                "verbose_name": "Посещение",
                "verbose_name_plural": "Посещения",
                "ordering": ["-occurred_at"],
            },
        ),
    ]
