# Generated by Django 5.2.5 on 2025-11-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="occasion",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="mediaitem",
            name="uploaded_by",
        ),
        migrations.AlterField(
            model_name="gallery",
            name="template_key",
            field=models.CharField(
                choices=[
                    ("valentine", "14 февраля"),
                    ("womens_day", "8 марта"),
                    ("birthday", "День рождения"),
                    ("anniversary", "Годовщина"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=32,
                verbose_name="Повод",
            ),
        ),
    ]
