# Generated by Django 5.2.5 on 2025-11-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_gallery_occasion_remove_gallery_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="template_key",
            field=models.CharField(
                choices=[
                    ("valentine", "14 февраля"),
                    ("womens_day", "8 марта"),
                    ("birthday", "День рождения"),
                    ("anniversary", "Годовщина"),
                    ("classic", "Классическая"),
                ],
                default="classic",
                max_length=32,
                verbose_name="Повод",
            ),
        ),
    ]
